version: '3.8'

services:
  octoprint:
    build:
      context: ./docker/octoprint
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - octoprint_data:/data
      - ./src/octoprint_mtconnect:/plugin
      - ./logs/octoprint:/var/log/octoprint
    environment:
      - ENABLE_VIRTUAL_PRINTER=true
      - PYTHONPATH=/plugin
    networks:
      mtconnect_net:
        aliases:
          - octoprint.local
          
  nodered:
    image: nodered/node-red:latest
    user: "0"
    ports:
      - "1880:1880"
      - "7878:7878"
    volumes:
      - nodered_data:/data
      - ./src/nodered:/data/nodes
      - ./docker/nodered/install-packages.sh:/data/install-packages.sh
    environment:
      - TZ=UTC
    networks:
      mtconnect_net:
        aliases:
          - nodered.local
    command: >
      sh -c "/data/install-packages.sh && 
             npm start -- --userDir /data"

  dev-tools:
    build:
      context: ./docker/dev-tools
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    ports:
      - "3000:3000"
    environment:
      - OCTOPRINT_HOST=octoprint.local
      - NODERED_HOST=nodered.local
    networks:
      - mtconnect_net

networks:
  mtconnect_net:
    driver: bridge

volumes:
  octoprint_data:
  nodered_data: